/* Generated By:JJTree: Do not edit this line. ASTAssertStatement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package uk.ac.open.crc.jim.parser.java14;

public
class ASTAssertStatement extends SimpleNode {
  public ASTAssertStatement(int id) {
    super(id);
  }

  public ASTAssertStatement(Java14Parser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTAssertStatement(id);
  }

  public static Node jjtCreate(Java14Parser p, int id) {
    return new ASTAssertStatement(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(Java14ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=07cfa553dbe808367d45617a48cb4c9b (do not edit this line) */
