/* Generated By:JJTree: Do not edit this line. ASTAnnotationTypeBody.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package uk.ac.open.crc.jim.parser.java14;

public
class ASTAnnotationTypeBody extends SimpleNode {
  public ASTAnnotationTypeBody(int id) {
    super(id);
  }

  public ASTAnnotationTypeBody(Java14Parser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTAnnotationTypeBody(id);
  }

  public static Node jjtCreate(Java14Parser p, int id) {
    return new ASTAnnotationTypeBody(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(Java14ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ae6ec691254ca9283e353e102a9f49f1 (do not edit this line) */
