/* Generated By:JJTree: Do not edit this line. ASTAtSign.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package uk.ac.open.crc.jim.parser.java14;

public
class ASTAtSign extends SimpleNode {
  public ASTAtSign(int id) {
    super(id);
  }

  public ASTAtSign(Java14Parser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTAtSign(id);
  }

  public static Node jjtCreate(Java14Parser p, int id) {
    return new ASTAtSign(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(Java14ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=73cec32dee66e47d9474389a09fbce13 (do not edit this line) */
