/* Generated By:JJTree: Do not edit this line. ASTCharacterLiteral.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package uk.ac.open.crc.jim.parser.java14;

public
class ASTCharacterLiteral extends SimpleNode {
  public ASTCharacterLiteral(int id) {
    super(id);
  }

  public ASTCharacterLiteral(Java14Parser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTCharacterLiteral(id);
  }

  public static Node jjtCreate(Java14Parser p, int id) {
    return new ASTCharacterLiteral(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(Java14ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=7aaec9e429d0dee527bc73e68b59b1b8 (do not edit this line) */
