/* Generated By:JJTree: Do not edit this line. ASTComma.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package uk.ac.open.crc.jim.parser.java14;

public
class ASTComma extends SimpleNode {
  public ASTComma(int id) {
    super(id);
  }

  public ASTComma(Java14Parser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTComma(id);
  }

  public static Node jjtCreate(Java14Parser p, int id) {
    return new ASTComma(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(Java14ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=36f785091ab4a27f02a513d9a83b0912 (do not edit this line) */
