/* Generated By:JJTree: Do not edit this line. ASTDot.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package uk.ac.open.crc.jim.parser.java14;

public
class ASTDot extends SimpleNode {
  public ASTDot(int id) {
    super(id);
  }

  public ASTDot(Java14Parser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTDot(id);
  }

  public static Node jjtCreate(Java14Parser p, int id) {
    return new ASTDot(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(Java14ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d1f4540927fa8d8eb2b2a64364c02658 (do not edit this line) */
