/* Generated By:JJTree: Do not edit this line. ASTDefaultValue.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package uk.ac.open.crc.jim.parser.java14;

public
class ASTDefaultValue extends SimpleNode {
  public ASTDefaultValue(int id) {
    super(id);
  }

  public ASTDefaultValue(Java14Parser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTDefaultValue(id);
  }

  public static Node jjtCreate(Java14Parser p, int id) {
    return new ASTDefaultValue(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(Java14ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9fcfa6959c40c81f2ff1d4f013c316b4 (do not edit this line) */
