/* Generated By:JJTree: Do not edit this line. ASTExtendsList.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package uk.ac.open.crc.jim.parser.java14;

public
class ASTExtendsList extends SimpleNode {
  public ASTExtendsList(int id) {
    super(id);
  }

  public ASTExtendsList(Java14Parser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTExtendsList(id);
  }

  public static Node jjtCreate(Java14Parser p, int id) {
    return new ASTExtendsList(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(Java14ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=bc17b8f7a34d66e4786b87d09725a1bf (do not edit this line) */
