/* Generated By:JJTree: Do not edit this line. ASTLeftParenthesis.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package uk.ac.open.crc.jim.parser.java14;

public
class ASTLeftParenthesis extends SimpleNode {
  public ASTLeftParenthesis(int id) {
    super(id);
  }

  public ASTLeftParenthesis(Java14Parser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTLeftParenthesis(id);
  }

  public static Node jjtCreate(Java14Parser p, int id) {
    return new ASTLeftParenthesis(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(Java14ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6f07ce4883870364c4f0aae82e24f50c (do not edit this line) */
