/* Generated By:JJTree: Do not edit this line. ASTLabeledStatement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package uk.ac.open.crc.jim.parser.java14;

public
class ASTLabeledStatement extends SimpleNode {
  public ASTLabeledStatement(int id) {
    super(id);
  }

  public ASTLabeledStatement(Java14Parser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTLabeledStatement(id);
  }

  public static Node jjtCreate(Java14Parser p, int id) {
    return new ASTLabeledStatement(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(Java14ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=5ff23e53afa7224e0e742eb167a805e0 (do not edit this line) */
