/* Generated By:JJTree: Do not edit this line. ASTLeftSquare.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package uk.ac.open.crc.jim.parser.java14;

public
class ASTLeftSquare extends SimpleNode {
  public ASTLeftSquare(int id) {
    super(id);
  }

  public ASTLeftSquare(Java14Parser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTLeftSquare(id);
  }

  public static Node jjtCreate(Java14Parser p, int id) {
    return new ASTLeftSquare(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(Java14ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=34c4aba429d13fc9cb0287a546644e73 (do not edit this line) */
