/* Generated By:JJTree: Do not edit this line. ASTLeftAngle.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package uk.ac.open.crc.jim.parser.java14;

public
class ASTLeftAngle extends SimpleNode {
  public ASTLeftAngle(int id) {
    super(id);
  }

  public ASTLeftAngle(Java14Parser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTLeftAngle(id);
  }

  public static Node jjtCreate(Java14Parser p, int id) {
    return new ASTLeftAngle(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(Java14ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=059d953c582abbe346c0722b478ab906 (do not edit this line) */
