/* Generated By:JJTree: Do not edit this line. ASTMemberValueArrayInitializer.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package uk.ac.open.crc.jim.parser.java14;

public
class ASTMemberValueArrayInitializer extends SimpleNode {
  public ASTMemberValueArrayInitializer(int id) {
    super(id);
  }

  public ASTMemberValueArrayInitializer(Java14Parser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTMemberValueArrayInitializer(id);
  }

  public static Node jjtCreate(Java14Parser p, int id) {
    return new ASTMemberValueArrayInitializer(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(Java14ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c0ce4486e139d8e0527936ffc018e2c6 (do not edit this line) */
