/* Generated By:JJTree: Do not edit this line. ASTPrimarySuffix.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package uk.ac.open.crc.jim.parser.java14;

public
class ASTPrimarySuffix extends SimpleNode {
  public ASTPrimarySuffix(int id) {
    super(id);
  }

  public ASTPrimarySuffix(Java14Parser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTPrimarySuffix(id);
  }

  public static Node jjtCreate(Java14Parser p, int id) {
    return new ASTPrimarySuffix(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(Java14ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4a0276d0899146e797a774413a55e324 (do not edit this line) */
