/* Generated By:JJTree: Do not edit this line. ASTPackageDeclaration.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package uk.ac.open.crc.jim.parser.java14;

public
class ASTPackageDeclaration extends SimpleNode {
  public ASTPackageDeclaration(int id) {
    super(id);
  }

  public ASTPackageDeclaration(Java14Parser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTPackageDeclaration(id);
  }

  public static Node jjtCreate(Java14Parser p, int id) {
    return new ASTPackageDeclaration(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(Java14ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3cf70cf37e6db77951724b97db9b0052 (do not edit this line) */
