/* Generated By:JJTree: Do not edit this line. ASTRightAngle.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package uk.ac.open.crc.jim.parser.java14;

public
class ASTRightAngle extends SimpleNode {
  public ASTRightAngle(int id) {
    super(id);
  }

  public ASTRightAngle(Java14Parser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTRightAngle(id);
  }

  public static Node jjtCreate(Java14Parser p, int id) {
    return new ASTRightAngle(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(Java14ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=dafede8ec145d1e8f49b97727c3797c2 (do not edit this line) */
