/* Generated By:JJTree: Do not edit this line. ASTRightSquare.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package uk.ac.open.crc.jim.parser.java14;

public
class ASTRightSquare extends SimpleNode {
  public ASTRightSquare(int id) {
    super(id);
  }

  public ASTRightSquare(Java14Parser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTRightSquare(id);
  }

  public static Node jjtCreate(Java14Parser p, int id) {
    return new ASTRightSquare(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(Java14ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e95a9f367f6b8124d027d4897f0a7e0c (do not edit this line) */
