/* Generated By:JJTree: Do not edit this line. ASTSingleMemberAnnotation.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package uk.ac.open.crc.jim.parser.java14;

public
class ASTSingleMemberAnnotation extends SimpleNode {
  public ASTSingleMemberAnnotation(int id) {
    super(id);
  }

  public ASTSingleMemberAnnotation(Java14Parser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTSingleMemberAnnotation(id);
  }

  public static Node jjtCreate(Java14Parser p, int id) {
    return new ASTSingleMemberAnnotation(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(Java14ParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3f84b3006e2a8b8ed800a68fd400c416 (do not edit this line) */
