/* Generated By:JJTree: Do not edit this line. ASTTypeParameters.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package uk.ac.open.crc.jim.parser.java14;

public
class ASTTypeParameters extends SimpleNode {
  public ASTTypeParameters(int id) {
    super(id);
  }

  public ASTTypeParameters(Java14Parser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTTypeParameters(id);
  }

  public static Node jjtCreate(Java14Parser p, int id) {
    return new ASTTypeParameters(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(Java14ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=03436df1684b31d5b04d22f1a50e0c79 (do not edit this line) */
