/* Generated By:JJTree: Do not edit this line. ASTTypeArguments.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package uk.ac.open.crc.jim.parser.java14;

public
class ASTTypeArguments extends SimpleNode {
  public ASTTypeArguments(int id) {
    super(id);
  }

  public ASTTypeArguments(Java14Parser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTTypeArguments(id);
  }

  public static Node jjtCreate(Java14Parser p, int id) {
    return new ASTTypeArguments(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(Java14ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=fab71e0a904ee5126490452d837850c9 (do not edit this line) */
