/* Generated By:JJTree: Do not edit this line. ASTVariableDeclarator.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package uk.ac.open.crc.jim.parser.java14;

public
class ASTVariableDeclarator extends SimpleNode {
  public ASTVariableDeclarator(int id) {
    super(id);
  }

  public ASTVariableDeclarator(Java14Parser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTVariableDeclarator(id);
  }

  public static Node jjtCreate(Java14Parser p, int id) {
    return new ASTVariableDeclarator(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(Java14ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d9b81eb9c035c7d28220aa3fe643b457 (do not edit this line) */
