/* Generated By:JJTree: Do not edit this line. ASTWildcardBounds.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package uk.ac.open.crc.jim.parser.java14;

public
class ASTWildcardBounds extends SimpleNode {
  public ASTWildcardBounds(int id) {
    super(id);
  }

  public ASTWildcardBounds(Java14Parser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTWildcardBounds(id);
  }

  public static Node jjtCreate(Java14Parser p, int id) {
    return new ASTWildcardBounds(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(Java14ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b803b2741cf7d85f703dbe8d520ba3a2 (do not edit this line) */
