/* Generated By:JavaCC: Do not edit this line. Java14ParserTreeConstants.java Version 6.0_1 */
package uk.ac.open.crc.jim.parser.java14;

public interface Java14ParserTreeConstants
{
  public int JJTCOMPILATIONUNIT = 0;
  public int JJTPACKAGEDECLARATION = 1;
  public int JJTIMPORTDECLARATION = 2;
  public int JJTMODIFIERS = 3;
  public int JJTTYPEDECLARATION = 4;
  public int JJTCLASSORINTERFACEDECLARATION = 5;
  public int JJTEXTENDSLIST = 6;
  public int JJTIMPLEMENTSLIST = 7;
  public int JJTTYPEPARAMETERS = 8;
  public int JJTTYPEPARAMETER = 9;
  public int JJTTYPEBOUND = 10;
  public int JJTCLASSORINTERFACEBODY = 11;
  public int JJTCLASSORINTERFACEBODYDECLARATION = 12;
  public int JJTFIELDDECLARATION = 13;
  public int JJTVARIABLEDECLARATOR = 14;
  public int JJTVARIABLEDECLARATORID = 15;
  public int JJTVARIABLEINITIALIZER = 16;
  public int JJTARRAYINITIALIZER = 17;
  public int JJTMETHODDECLARATION = 18;
  public int JJTMETHODDECLARATOR = 19;
  public int JJTFORMALPARAMETERS = 20;
  public int JJTFORMALPARAMETER = 21;
  public int JJTCONSTRUCTORDECLARATION = 22;
  public int JJTEXPLICITCONSTRUCTORINVOCATION = 23;
  public int JJTINITIALIZER = 24;
  public int JJTTYPE = 25;
  public int JJTREFERENCETYPE = 26;
  public int JJTCLASSORINTERFACETYPE = 27;
  public int JJTTYPEARGUMENTS = 28;
  public int JJTTYPEARGUMENT = 29;
  public int JJTWILDCARDBOUNDS = 30;
  public int JJTPRIMITIVETYPE = 31;
  public int JJTRESULTTYPE = 32;
  public int JJTNAME = 33;
  public int JJTNAMELIST = 34;
  public int JJTEXPRESSION = 35;
  public int JJTASSIGNMENTOPERATOR = 36;
  public int JJTCONDITIONALEXPRESSION = 37;
  public int JJTCONDITIONALOREXPRESSION = 38;
  public int JJTCONDITIONALANDEXPRESSION = 39;
  public int JJTINCLUSIVEOREXPRESSION = 40;
  public int JJTEXCLUSIVEOREXPRESSION = 41;
  public int JJTANDEXPRESSION = 42;
  public int JJTEQUALITYEXPRESSION = 43;
  public int JJTINSTANCEOFEXPRESSION = 44;
  public int JJTRELATIONALEXPRESSION = 45;
  public int JJTSHIFTEXPRESSION = 46;
  public int JJTADDITIVEEXPRESSION = 47;
  public int JJTMULTIPLICATIVEEXPRESSION = 48;
  public int JJTUNARYEXPRESSION = 49;
  public int JJTPREINCREMENTEXPRESSION = 50;
  public int JJTPREDECREMENTEXPRESSION = 51;
  public int JJTUNARYEXPRESSIONNOTPLUSMINUS = 52;
  public int JJTCASTLOOKAHEAD = 53;
  public int JJTPOSTFIXEXPRESSION = 54;
  public int JJTCASTEXPRESSION = 55;
  public int JJTPRIMARYEXPRESSION = 56;
  public int JJTMEMBERSELECTOR = 57;
  public int JJTPRIMARYPREFIX = 58;
  public int JJTPRIMARYSUFFIX = 59;
  public int JJTLITERAL = 60;
  public int JJTSTRINGLITERAL = 61;
  public int JJTCHARACTERLITERAL = 62;
  public int JJTFLOATINGPOINTLITERAL = 63;
  public int JJTINTEGERLITERAL = 64;
  public int JJTBOOLEANLITERAL = 65;
  public int JJTNULLLITERAL = 66;
  public int JJTARGUMENTS = 67;
  public int JJTARGUMENTLIST = 68;
  public int JJTALLOCATIONEXPRESSION = 69;
  public int JJTARRAYDIMSANDINITS = 70;
  public int JJTSTATEMENT = 71;
  public int JJTASSERTSTATEMENT = 72;
  public int JJTLABELEDSTATEMENT = 73;
  public int JJTBLOCK = 74;
  public int JJTBLOCKSTATEMENT = 75;
  public int JJTLOCALVARIABLEDECLARATION = 76;
  public int JJTEMPTYSTATEMENT = 77;
  public int JJTSTATEMENTEXPRESSION = 78;
  public int JJTSWITCHSTATEMENT = 79;
  public int JJTSWITCHLABEL = 80;
  public int JJTCASELABEL = 81;
  public int JJTDEFAULTLABEL = 82;
  public int JJTIFSTATEMENT = 83;
  public int JJTWHILESTATEMENT = 84;
  public int JJTDOSTATEMENT = 85;
  public int JJTFORSTATEMENT = 86;
  public int JJTFORINIT = 87;
  public int JJTSTATEMENTEXPRESSIONLIST = 88;
  public int JJTFORUPDATE = 89;
  public int JJTBREAKSTATEMENT = 90;
  public int JJTCONTINUESTATEMENT = 91;
  public int JJTRETURNSTATEMENT = 92;
  public int JJTTHROWSTATEMENT = 93;
  public int JJTSYNCHRONIZEDSTATEMENT = 94;
  public int JJTTRYSTATEMENT = 95;
  public int JJTCATCHCLAUSE = 96;
  public int JJTRUNSIGNEDSHIFT = 97;
  public int JJTRSIGNEDSHIFT = 98;
  public int JJTIDENTIFIER = 99;
  public int JJTLEFTPARENTHESIS = 100;
  public int JJTRIGHTPARENTHESIS = 101;
  public int JJTLEFTBRACE = 102;
  public int JJTRIGHTBRACE = 103;
  public int JJTLEFTANGLE = 104;
  public int JJTRIGHTANGLE = 105;
  public int JJTLEFTSQUARE = 106;
  public int JJTRIGHTSQUARE = 107;
  public int JJTSEMICOLON = 108;
  public int JJTCOLON = 109;
  public int JJTASSIGNMENT = 110;
  public int JJTCOMMA = 111;
  public int JJTDOT = 112;
  public int JJTATSIGN = 113;
  public int JJTSTARWILDCARD = 114;


  public String[] jjtNodeName = {
    "CompilationUnit",
    "PackageDeclaration",
    "ImportDeclaration",
    "Modifiers",
    "TypeDeclaration",
    "ClassOrInterfaceDeclaration",
    "ExtendsList",
    "ImplementsList",
    "TypeParameters",
    "TypeParameter",
    "TypeBound",
    "ClassOrInterfaceBody",
    "ClassOrInterfaceBodyDeclaration",
    "FieldDeclaration",
    "VariableDeclarator",
    "VariableDeclaratorId",
    "VariableInitializer",
    "ArrayInitializer",
    "MethodDeclaration",
    "MethodDeclarator",
    "FormalParameters",
    "FormalParameter",
    "ConstructorDeclaration",
    "ExplicitConstructorInvocation",
    "Initializer",
    "Type",
    "ReferenceType",
    "ClassOrInterfaceType",
    "TypeArguments",
    "TypeArgument",
    "WildcardBounds",
    "PrimitiveType",
    "ResultType",
    "Name",
    "NameList",
    "Expression",
    "AssignmentOperator",
    "ConditionalExpression",
    "ConditionalOrExpression",
    "ConditionalAndExpression",
    "InclusiveOrExpression",
    "ExclusiveOrExpression",
    "AndExpression",
    "EqualityExpression",
    "InstanceOfExpression",
    "RelationalExpression",
    "ShiftExpression",
    "AdditiveExpression",
    "MultiplicativeExpression",
    "UnaryExpression",
    "PreIncrementExpression",
    "PreDecrementExpression",
    "UnaryExpressionNotPlusMinus",
    "CastLookahead",
    "PostfixExpression",
    "CastExpression",
    "PrimaryExpression",
    "MemberSelector",
    "PrimaryPrefix",
    "PrimarySuffix",
    "Literal",
    "StringLiteral",
    "CharacterLiteral",
    "FloatingPointLiteral",
    "IntegerLiteral",
    "BooleanLiteral",
    "NullLiteral",
    "Arguments",
    "ArgumentList",
    "AllocationExpression",
    "ArrayDimsAndInits",
    "Statement",
    "AssertStatement",
    "LabeledStatement",
    "Block",
    "BlockStatement",
    "LocalVariableDeclaration",
    "EmptyStatement",
    "StatementExpression",
    "SwitchStatement",
    "SwitchLabel",
    "CaseLabel",
    "DefaultLabel",
    "IfStatement",
    "WhileStatement",
    "DoStatement",
    "ForStatement",
    "ForInit",
    "StatementExpressionList",
    "ForUpdate",
    "BreakStatement",
    "ContinueStatement",
    "ReturnStatement",
    "ThrowStatement",
    "SynchronizedStatement",
    "TryStatement",
    "CatchClause",
    "RUNSIGNEDSHIFT",
    "RSIGNEDSHIFT",
    "Identifier",
    "LeftParenthesis",
    "RightParenthesis",
    "LeftBrace",
    "RightBrace",
    "LeftAngle",
    "RightAngle",
    "LeftSquare",
    "RightSquare",
    "SemiColon",
    "Colon",
    "Assignment",
    "Comma",
    "Dot",
    "AtSign",
    "StarWildcard",
  };
}
/* JavaCC - OriginalChecksum=45f977b1af49638b9290a335a8a78988 (do not edit this line) */
