/* Generated By:JJTree: Do not edit this line. ASTAllocationExpression.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package uk.ac.open.crc.jim.parser.java15;

public
class ASTAllocationExpression extends SimpleNode {
  public ASTAllocationExpression(int id) {
    super(id);
  }

  public ASTAllocationExpression(Java15Parser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTAllocationExpression(id);
  }

  public static Node jjtCreate(Java15Parser p, int id) {
    return new ASTAllocationExpression(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(Java15ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=57c791ebdfc23b7ff16161ce87842104 (do not edit this line) */
