/* Generated By:JJTree: Do not edit this line. ASTColon.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package uk.ac.open.crc.jim.parser.java15;

public
class ASTColon extends SimpleNode {
  public ASTColon(int id) {
    super(id);
  }

  public ASTColon(Java15Parser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTColon(id);
  }

  public static Node jjtCreate(Java15Parser p, int id) {
    return new ASTColon(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(Java15ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=5cd849d63dc952f7e4c892c3579ad1c3 (do not edit this line) */
