/* Generated By:JJTree: Do not edit this line. ASTClassOrInterfaceBodyDeclaration.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package uk.ac.open.crc.jim.parser.java15;

public
class ASTClassOrInterfaceBodyDeclaration extends SimpleNode {
  public ASTClassOrInterfaceBodyDeclaration(int id) {
    super(id);
  }

  public ASTClassOrInterfaceBodyDeclaration(Java15Parser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTClassOrInterfaceBodyDeclaration(id);
  }

  public static Node jjtCreate(Java15Parser p, int id) {
    return new ASTClassOrInterfaceBodyDeclaration(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(Java15ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d1771c408530dea1511fc2de774c2400 (do not edit this line) */
