/* Generated By:JJTree: Do not edit this line. ASTCatchClause.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package uk.ac.open.crc.jim.parser.java15;

public
class ASTCatchClause extends SimpleNode {
  public ASTCatchClause(int id) {
    super(id);
  }

  public ASTCatchClause(Java15Parser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTCatchClause(id);
  }

  public static Node jjtCreate(Java15Parser p, int id) {
    return new ASTCatchClause(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(Java15ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c21dc5e63206b189ddf2c4f6f1761ad2 (do not edit this line) */
