/* Generated By:JJTree: Do not edit this line. ASTClassOrInterfaceBody.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package uk.ac.open.crc.jim.parser.java15;

public
class ASTClassOrInterfaceBody extends SimpleNode {
  public ASTClassOrInterfaceBody(int id) {
    super(id);
  }

  public ASTClassOrInterfaceBody(Java15Parser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTClassOrInterfaceBody(id);
  }

  public static Node jjtCreate(Java15Parser p, int id) {
    return new ASTClassOrInterfaceBody(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(Java15ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=cd0224f66e71f50016fae96afe993b25 (do not edit this line) */
