/* Generated By:JJTree: Do not edit this line. ASTEnumConstant.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package uk.ac.open.crc.jim.parser.java15;

public
class ASTEnumConstant extends SimpleNode {
  public ASTEnumConstant(int id) {
    super(id);
  }

  public ASTEnumConstant(Java15Parser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTEnumConstant(id);
  }

  public static Node jjtCreate(Java15Parser p, int id) {
    return new ASTEnumConstant(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(Java15ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8560e341da551567ce36d8a9926cdad9 (do not edit this line) */
