/* Generated By:JJTree: Do not edit this line. ASTFloatingPointLiteral.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package uk.ac.open.crc.jim.parser.java15;

public
class ASTFloatingPointLiteral extends SimpleNode {
  public ASTFloatingPointLiteral(int id) {
    super(id);
  }

  public ASTFloatingPointLiteral(Java15Parser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTFloatingPointLiteral(id);
  }

  public static Node jjtCreate(Java15Parser p, int id) {
    return new ASTFloatingPointLiteral(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(Java15ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9c0cd3452d5fa23a7f69e6e93624e420 (do not edit this line) */
