/* Generated By:JJTree: Do not edit this line. ASTLeftSquare.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package uk.ac.open.crc.jim.parser.java15;

public
class ASTLeftSquare extends SimpleNode {
  public ASTLeftSquare(int id) {
    super(id);
  }

  public ASTLeftSquare(Java15Parser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTLeftSquare(id);
  }

  public static Node jjtCreate(Java15Parser p, int id) {
    return new ASTLeftSquare(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(Java15ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b4219e072c4f3ac3a7ae7b99d22657f2 (do not edit this line) */
