/* Generated By:JJTree: Do not edit this line. ASTMemberValueArrayInitializer.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package uk.ac.open.crc.jim.parser.java15;

public
class ASTMemberValueArrayInitializer extends SimpleNode {
  public ASTMemberValueArrayInitializer(int id) {
    super(id);
  }

  public ASTMemberValueArrayInitializer(Java15Parser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTMemberValueArrayInitializer(id);
  }

  public static Node jjtCreate(Java15Parser p, int id) {
    return new ASTMemberValueArrayInitializer(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(Java15ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=01be7599afbe7b0215650ca442a64dc7 (do not edit this line) */
