/* Generated By:JJTree: Do not edit this line. ASTMemberSelector.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package uk.ac.open.crc.jim.parser.java15;

public
class ASTMemberSelector extends SimpleNode {
  public ASTMemberSelector(int id) {
    super(id);
  }

  public ASTMemberSelector(Java15Parser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTMemberSelector(id);
  }

  public static Node jjtCreate(Java15Parser p, int id) {
    return new ASTMemberSelector(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(Java15ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3965f9ad24ef855f08aefbbc42f5bda1 (do not edit this line) */
