/* Generated By:JJTree: Do not edit this line. ASTMemberValue.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package uk.ac.open.crc.jim.parser.java15;

public
class ASTMemberValue extends SimpleNode {
  public ASTMemberValue(int id) {
    super(id);
  }

  public ASTMemberValue(Java15Parser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTMemberValue(id);
  }

  public static Node jjtCreate(Java15Parser p, int id) {
    return new ASTMemberValue(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(Java15ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0ef2957955de47d34cc285d94f9c7484 (do not edit this line) */
