/* Generated By:JJTree: Do not edit this line. ASTRUNSIGNEDSHIFT.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package uk.ac.open.crc.jim.parser.java15;

public
class ASTRUNSIGNEDSHIFT extends SimpleNode {
  public ASTRUNSIGNEDSHIFT(int id) {
    super(id);
  }

  public ASTRUNSIGNEDSHIFT(Java15Parser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTRUNSIGNEDSHIFT(id);
  }

  public static Node jjtCreate(Java15Parser p, int id) {
    return new ASTRUNSIGNEDSHIFT(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(Java15ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=93fc302a08e6fadc8656b90ff514f83a (do not edit this line) */
