/* Generated By:JJTree: Do not edit this line. ASTSynchronizedStatement.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package uk.ac.open.crc.jim.parser.java15;

public
class ASTSynchronizedStatement extends SimpleNode {
  public ASTSynchronizedStatement(int id) {
    super(id);
  }

  public ASTSynchronizedStatement(Java15Parser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTSynchronizedStatement(id);
  }

  public static Node jjtCreate(Java15Parser p, int id) {
    return new ASTSynchronizedStatement(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(Java15ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3b26620949689fd82fe2b22fa414c4db (do not edit this line) */
