/* Generated By:JJTree: Do not edit this line. ASTTypeArguments.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=*,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package uk.ac.open.crc.jim.parser.java15;

public
class ASTTypeArguments extends SimpleNode {
  public ASTTypeArguments(int id) {
    super(id);
  }

  public ASTTypeArguments(Java15Parser p, int id) {
    super(p, id);
  }

  public static Node jjtCreate(int id) {
    return new ASTTypeArguments(id);
  }

  public static Node jjtCreate(Java15Parser p, int id) {
    return new ASTTypeArguments(p, id);
  }

  /** Accept the visitor. **/
  public Object jjtAccept(Java15ParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=026c83134fc1da7402a3982b3c3d8962 (do not edit this line) */
