/* Generated By:JavaCC: Do not edit this line. Java15ParserTreeConstants.java Version 6.0_1 */
package uk.ac.open.crc.jim.parser.java15;

public interface Java15ParserTreeConstants
{
  public int JJTCOMPILATIONUNIT = 0;
  public int JJTPACKAGEDECLARATION = 1;
  public int JJTIMPORTDECLARATION = 2;
  public int JJTMODIFIERS = 3;
  public int JJTTYPEDECLARATION = 4;
  public int JJTCLASSORINTERFACEDECLARATION = 5;
  public int JJTEXTENDSLIST = 6;
  public int JJTIMPLEMENTSLIST = 7;
  public int JJTENUMDECLARATION = 8;
  public int JJTENUMBODY = 9;
  public int JJTENUMCONSTANT = 10;
  public int JJTTYPEPARAMETERS = 11;
  public int JJTTYPEPARAMETER = 12;
  public int JJTTYPEBOUND = 13;
  public int JJTCLASSORINTERFACEBODY = 14;
  public int JJTCLASSORINTERFACEBODYDECLARATION = 15;
  public int JJTFIELDDECLARATION = 16;
  public int JJTVARIABLEDECLARATOR = 17;
  public int JJTVARIABLEDECLARATORID = 18;
  public int JJTVARIABLEINITIALIZER = 19;
  public int JJTARRAYINITIALIZER = 20;
  public int JJTMETHODDECLARATION = 21;
  public int JJTMETHODDECLARATOR = 22;
  public int JJTFORMALPARAMETERS = 23;
  public int JJTFORMALPARAMETER = 24;
  public int JJTCONSTRUCTORDECLARATION = 25;
  public int JJTEXPLICITCONSTRUCTORINVOCATION = 26;
  public int JJTINITIALIZER = 27;
  public int JJTTYPE = 28;
  public int JJTREFERENCETYPE = 29;
  public int JJTCLASSORINTERFACETYPE = 30;
  public int JJTTYPEARGUMENTS = 31;
  public int JJTTYPEARGUMENT = 32;
  public int JJTWILDCARDBOUNDS = 33;
  public int JJTPRIMITIVETYPE = 34;
  public int JJTRESULTTYPE = 35;
  public int JJTNAME = 36;
  public int JJTNAMELIST = 37;
  public int JJTEXPRESSION = 38;
  public int JJTASSIGNMENTOPERATOR = 39;
  public int JJTCONDITIONALEXPRESSION = 40;
  public int JJTCONDITIONALOREXPRESSION = 41;
  public int JJTCONDITIONALANDEXPRESSION = 42;
  public int JJTINCLUSIVEOREXPRESSION = 43;
  public int JJTEXCLUSIVEOREXPRESSION = 44;
  public int JJTANDEXPRESSION = 45;
  public int JJTEQUALITYEXPRESSION = 46;
  public int JJTINSTANCEOFEXPRESSION = 47;
  public int JJTRELATIONALEXPRESSION = 48;
  public int JJTSHIFTEXPRESSION = 49;
  public int JJTADDITIVEEXPRESSION = 50;
  public int JJTMULTIPLICATIVEEXPRESSION = 51;
  public int JJTUNARYEXPRESSION = 52;
  public int JJTPREINCREMENTEXPRESSION = 53;
  public int JJTPREDECREMENTEXPRESSION = 54;
  public int JJTUNARYEXPRESSIONNOTPLUSMINUS = 55;
  public int JJTCASTLOOKAHEAD = 56;
  public int JJTPOSTFIXEXPRESSION = 57;
  public int JJTCASTEXPRESSION = 58;
  public int JJTPRIMARYEXPRESSION = 59;
  public int JJTMEMBERSELECTOR = 60;
  public int JJTPRIMARYPREFIX = 61;
  public int JJTPRIMARYSUFFIX = 62;
  public int JJTLITERAL = 63;
  public int JJTSTRINGLITERAL = 64;
  public int JJTCHARACTERLITERAL = 65;
  public int JJTFLOATINGPOINTLITERAL = 66;
  public int JJTINTEGERLITERAL = 67;
  public int JJTBOOLEANLITERAL = 68;
  public int JJTNULLLITERAL = 69;
  public int JJTARGUMENTS = 70;
  public int JJTARGUMENTLIST = 71;
  public int JJTALLOCATIONEXPRESSION = 72;
  public int JJTARRAYDIMSANDINITS = 73;
  public int JJTSTATEMENT = 74;
  public int JJTASSERTSTATEMENT = 75;
  public int JJTLABELEDSTATEMENT = 76;
  public int JJTBLOCK = 77;
  public int JJTBLOCKSTATEMENT = 78;
  public int JJTLOCALVARIABLEDECLARATION = 79;
  public int JJTEMPTYSTATEMENT = 80;
  public int JJTSTATEMENTEXPRESSION = 81;
  public int JJTSWITCHSTATEMENT = 82;
  public int JJTSWITCHLABEL = 83;
  public int JJTCASELABEL = 84;
  public int JJTDEFAULTLABEL = 85;
  public int JJTIFSTATEMENT = 86;
  public int JJTWHILESTATEMENT = 87;
  public int JJTDOSTATEMENT = 88;
  public int JJTFORSTATEMENT = 89;
  public int JJTFORINIT = 90;
  public int JJTSTATEMENTEXPRESSIONLIST = 91;
  public int JJTFORUPDATE = 92;
  public int JJTBREAKSTATEMENT = 93;
  public int JJTCONTINUESTATEMENT = 94;
  public int JJTRETURNSTATEMENT = 95;
  public int JJTTHROWSTATEMENT = 96;
  public int JJTSYNCHRONIZEDSTATEMENT = 97;
  public int JJTTRYSTATEMENT = 98;
  public int JJTCATCHCLAUSE = 99;
  public int JJTRUNSIGNEDSHIFT = 100;
  public int JJTRSIGNEDSHIFT = 101;
  public int JJTANNOTATION = 102;
  public int JJTNORMALANNOTATION = 103;
  public int JJTMARKERANNOTATION = 104;
  public int JJTSINGLEMEMBERANNOTATION = 105;
  public int JJTMEMBERVALUEPAIRS = 106;
  public int JJTMEMBERVALUEPAIR = 107;
  public int JJTMEMBERVALUE = 108;
  public int JJTMEMBERVALUEARRAYINITIALIZER = 109;
  public int JJTANNOTATIONTYPEDECLARATION = 110;
  public int JJTANNOTATIONTYPEBODY = 111;
  public int JJTANNOTATIONTYPEMEMBERDECLARATION = 112;
  public int JJTDEFAULTVALUE = 113;
  public int JJTIDENTIFIER = 114;
  public int JJTLEFTPARENTHESIS = 115;
  public int JJTRIGHTPARENTHESIS = 116;
  public int JJTLEFTBRACE = 117;
  public int JJTRIGHTBRACE = 118;
  public int JJTLEFTANGLE = 119;
  public int JJTRIGHTANGLE = 120;
  public int JJTLEFTSQUARE = 121;
  public int JJTRIGHTSQUARE = 122;
  public int JJTSEMICOLON = 123;
  public int JJTCOLON = 124;
  public int JJTASSIGNMENT = 125;
  public int JJTCOMMA = 126;
  public int JJTDOT = 127;
  public int JJTATSIGN = 128;
  public int JJTSTARWILDCARD = 129;


  public String[] jjtNodeName = {
    "CompilationUnit",
    "PackageDeclaration",
    "ImportDeclaration",
    "Modifiers",
    "TypeDeclaration",
    "ClassOrInterfaceDeclaration",
    "ExtendsList",
    "ImplementsList",
    "EnumDeclaration",
    "EnumBody",
    "EnumConstant",
    "TypeParameters",
    "TypeParameter",
    "TypeBound",
    "ClassOrInterfaceBody",
    "ClassOrInterfaceBodyDeclaration",
    "FieldDeclaration",
    "VariableDeclarator",
    "VariableDeclaratorId",
    "VariableInitializer",
    "ArrayInitializer",
    "MethodDeclaration",
    "MethodDeclarator",
    "FormalParameters",
    "FormalParameter",
    "ConstructorDeclaration",
    "ExplicitConstructorInvocation",
    "Initializer",
    "Type",
    "ReferenceType",
    "ClassOrInterfaceType",
    "TypeArguments",
    "TypeArgument",
    "WildcardBounds",
    "PrimitiveType",
    "ResultType",
    "Name",
    "NameList",
    "Expression",
    "AssignmentOperator",
    "ConditionalExpression",
    "ConditionalOrExpression",
    "ConditionalAndExpression",
    "InclusiveOrExpression",
    "ExclusiveOrExpression",
    "AndExpression",
    "EqualityExpression",
    "InstanceOfExpression",
    "RelationalExpression",
    "ShiftExpression",
    "AdditiveExpression",
    "MultiplicativeExpression",
    "UnaryExpression",
    "PreIncrementExpression",
    "PreDecrementExpression",
    "UnaryExpressionNotPlusMinus",
    "CastLookahead",
    "PostfixExpression",
    "CastExpression",
    "PrimaryExpression",
    "MemberSelector",
    "PrimaryPrefix",
    "PrimarySuffix",
    "Literal",
    "StringLiteral",
    "CharacterLiteral",
    "FloatingPointLiteral",
    "IntegerLiteral",
    "BooleanLiteral",
    "NullLiteral",
    "Arguments",
    "ArgumentList",
    "AllocationExpression",
    "ArrayDimsAndInits",
    "Statement",
    "AssertStatement",
    "LabeledStatement",
    "Block",
    "BlockStatement",
    "LocalVariableDeclaration",
    "EmptyStatement",
    "StatementExpression",
    "SwitchStatement",
    "SwitchLabel",
    "CaseLabel",
    "DefaultLabel",
    "IfStatement",
    "WhileStatement",
    "DoStatement",
    "ForStatement",
    "ForInit",
    "StatementExpressionList",
    "ForUpdate",
    "BreakStatement",
    "ContinueStatement",
    "ReturnStatement",
    "ThrowStatement",
    "SynchronizedStatement",
    "TryStatement",
    "CatchClause",
    "RUNSIGNEDSHIFT",
    "RSIGNEDSHIFT",
    "Annotation",
    "NormalAnnotation",
    "MarkerAnnotation",
    "SingleMemberAnnotation",
    "MemberValuePairs",
    "MemberValuePair",
    "MemberValue",
    "MemberValueArrayInitializer",
    "AnnotationTypeDeclaration",
    "AnnotationTypeBody",
    "AnnotationTypeMemberDeclaration",
    "DefaultValue",
    "Identifier",
    "LeftParenthesis",
    "RightParenthesis",
    "LeftBrace",
    "RightBrace",
    "LeftAngle",
    "RightAngle",
    "LeftSquare",
    "RightSquare",
    "SemiColon",
    "Colon",
    "Assignment",
    "Comma",
    "Dot",
    "AtSign",
    "StarWildcard",
  };
}
/* JavaCC - OriginalChecksum=cba9ac34ae0831ecc76736f97b11299c (do not edit this line) */
